### PR TITLE
CakePHP 3.6.6 Required changes

### PR DESCRIPTION
**Pull request by pedro-stanaka**
Recently I upgraded my application to CakePHP 3.6.6 and in that version they introduced the concept of Plugin objects. With that they deprecated the Plugin::routes() method which was called on `config/routes.php` of cake applications, since the default way of loading routes is not through Plugin objects.

This PR the new Plugin object class to Swagger CakePHP, making it more compatible with CakePHP 3.6 and not requiring from users to keep deprecated code in their codebases.

P.S. If we remove the Plugin::routes() from `config/routes.php` in the application then we can't access the routes and the configuration file is not loaded, so basically everything breaks from console commands to UI.

### CODE REVIEW

**Comment by pedro-stanaka** [comment]
UPDATE: This is working on production!!! 🍾

**Comment by bravo-kernel** [comment]
@pedro-stanaka apologies for the late reply. Merging.

**Comment by bravo-kernel** [comment]
https://github.com/alt3/cakephp-swagger/releases/tag/2.0.1

**Comment by bravo-kernel** [comment]
After configuring the plugin for CakePHP 3.6+ following your new readme instructions:

1. I browse to `http://my.api/alt3/swagger`
2. the page/html gets generated correctly by the UiController
3. the links to the assets look good (e.g. `http://my.api/alt3/swagger/css/typography.css`)

However, all assets produce a 404 with the following CakePHP message:

> Error: Missing Route

Any pointers? This should "just work", especially for new users.

**Comment by bravo-kernel** [comment]
Ok, I totally missed the 3.6.6 exact requirement.  

Problem was caused by me still running on 3.6.4

This does bring a problem, do you agree we should have updated composer requirement as well?

**Comment by bravo-kernel** [comment]
I have removed the release, new PR coming up.

**Pull request merged**
