### PR TITLE
Allow to modify API basePath via annoations

### LINKED ISSUE #29: Allow to modify API basePath via annotations
Hey,

First of all, thanks for the plugin!

Having the API basePath derived from Configure::read('App.base') is good, but if you have an application where your API endpoints are prefixed (e.g. /api) and this app also serves static content or crud as the webpages this might be an issue.
So, having an option to define API basePath via annotations might help. Basically, if basePath is defined via annotations we use it or App.base otherwise.

The fix is quite trivial but I can create a PR if needed.
Thanks!

### PR DESCRIPTION
**Pull request by aleks-fofanov**
PR resolves #29

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Thanks, would you be so kind as to create a mention of this somewhere in the readme?

**Comment by aleks-fofanov** [comment]
Done.

**Comment by bravo-kernel** [comment]
Thanks, very nice job. Much obliged 👏

**Comment by bravo-kernel** [comment]
Released https://github.com/alt3/cakephp-swagger/releases/tag/1.0.2

**Pull request merged**
