### PR TITLE
Add support for providing custom Analyser object

### PR DESCRIPTION
**Pull request by georgeconstantinou**
You can provide a custom swagger Analyser class using Swagger configuration as follows:

```php
<?php
use App\Swagger\MyCustomAnalyser;

return [
    'Swagger' => [
        'analyser' => new MyCustomAnalyser()
    ]
];

```

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Do I understand correctly that this will allow one to automatically generate the swagger spec from the code? If so, that would be an amazing feature and one I am happy to merge in.

The failing tests seem unrelated, let me see if I can solve those first.

**Comment by bravo-kernel** [comment]
@georgeconstantinou I solved the travis issues, could you please trigger a commit?

**Comment by georgeconstantinou** [comment]
@bravo-kernel can you trigger the build without a commit by going [here](https://travis-ci.org/alt3/cakephp-swagger/builds/209676021) and pressing `Restart build` button in the top right?

**Comment by bravo-kernel** [comment]
Neat trick, thanks ☺️

**Comment by bravo-kernel** [comment]
@georgeconstantinou a rebase against current master is required (because of travis), could you please do that?

**Comment by georgeconstantinou** [comment]
@bravo-kernel in our scenario we have swagger annotations generated on the fly. In order for swagger to pick them up we implemented our own Analyser. Swagger supports alternative locations via the analyser, that is why we need this option.

**Comment by bravo-kernel** [comment]
OK, that sounds like the killer feature we all have been longing for. Is that Analyser logic available for us?

**Comment by georgeconstantinou** [comment]
@bravo-kernel we actually built the whole thing based on your [tutorial](http://www.bravo-kernel.com/2015/04/how-to-prefix-route-a-cakephp-3-rest-api/) (thank you very much). All the code is in this [PR](https://github.com/QoboLtd/cakephp-csv-migrations/pull/375/) to our sub-system. If you need any assistance just let me know.

**Comment by bravo-kernel** [comment]
@georgeconstantinou sorry, I should have taken more time to read the PR you referenced to, the analyser is right there. Thanks for the PR.

**Comment by georgeconstantinou** [comment]
@bravo-kernel can you please tag the new version?

**Comment by bravo-kernel** [comment]
Awesome, I might ping you if I need help, automated annotations have been on my list for soooo long ;)

**Comment by bravo-kernel** [comment]
https://github.com/alt3/cakephp-swagger/releases/tag/1.0.4, thanks a lot 💯

**Comment by georgeconstantinou** [comment]
@bravo-kernel thanks a lot, much appreciated

**Pull request merged**
