### PR TITLE
CakePHP 3.6 Support

### PR DESCRIPTION
**Pull request by pedro-stanaka**
Making the plugin use the latest CakePHP version and improving documentation of some classes.
Also fixed StyleCI config which included a deprecated option.

Summary of the work:
* Fixing deprecations of methods used in the Controllers (Docs and UI)
* Fixing deprecations in test code
* Using middlewares to execute integration tests
* Fixing StyleCI configuration ([more info](https://styleci.readme.io/docs/change-log#section-14042018-april-fixer-updates))

### CODE REVIEW

**Comment by pedro-stanaka** [comment]
@bravo-kernel it seems like styleCI is misconfigured, since phpcs pass with flying colors but that doesn't. What about setting up an integration with SticklerCI? This is what CakePHP core is using and most of the heavy Cake plugins as well. Just an opinion 😉

**Comment by bravo-kernel** [comment]
@pedro-stanaka thanks for the PR, awesome job. I have disabled styleci as it is totally unneeded. Could you please remove the `.styleci.yml` file so we can trigger the rebuild?

**Comment by pedro-stanaka** [comment]
@bravo-kernel there you go.

**Comment by bravo-kernel** [comment]
Thanks mr. @pedro-stanaka, very good job, much appreciated. Do you have a Twitter so I can mention you when I create the new release?

**Comment by bravo-kernel** [comment]
https://github.com/alt3/cakephp-swagger/releases/tag/2.0.0

**Comment by bravo-kernel** [comment]
ping, twitter?

**Pull request merged**
