### PR TITLE
Improves (new) Plugin Object configuration instructions

### PR DESCRIPTION
**Pull request by bravo-kernel**
Improves new Plugin Object instrutions.

### CODE REVIEW

**Comment by bravo-kernel** [comment]
@pedro-stanaka please review, would appreciate your feedback

**Comment by bravo-kernel** [comment]
Still getting 404 errors on the assets locally, must be something in my application. Any pointers welcome.

**Comment by pedro-stanaka** [comment]
This is okay @bravo-kernel, better wording on the readme. I liked. Are you going to bump major?

**Comment by bravo-kernel** [comment]
I think this should become 2.1.0 once I get those 404s out of the way.

**Comment by bravo-kernel** [comment]
Moved `parent::bootstrap();` to top as described in the book at https://book.cakephp.org/3.0/en/plugins.html#loading-a-plugin

**Comment by bravo-kernel** [comment]
@pedro-stanaka solved, assetMiddleware MUST be loaded (ofcourse), adding it to the README now

**Comment by bravo-kernel** [comment]
@pedro-stanaka please help me out here, or contact me on Slack to discuss. Just switched back to Cake 3.6.4 and all works as well there. So maybe no need to require CakePHP 3.6.6.

**Comment by pedro-stanaka** [comment]
Now that we changed the way we load the routes and assets. I think that is okay. I mean, it should work with 3.6.4.

**Comment by bravo-kernel** [comment]
OK, I will limit this to an update of the README then and will release 2.0.2 as soon as Travis turns green. Good job @pedro-stanaka and apologies for the noise, it's a bit hard to really focus sometimes due to lack of time.

**Comment by pedro-stanaka** [comment]
Yeah, I appreciate people like you that takes time to give back to the community @bravo-kernel ! Sorry for the delay as well! Have a nice day!

**Comment by bravo-kernel** [comment]
https://github.com/alt3/cakephp-swagger/releases/tag/2.0.2

**Pull request merged**
