### PR TITLE
cakePHP 4.x compatiblity

### LINKED ISSUE #51: Add suport for cakephp 4

### PR DESCRIPTION
**Pull request by mimorocks**
proposing new branch cake-4.x

fixes #51

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Thanks, looks like the test-suite needs updating as well. If you manage to get this all green I will release a new version. ❤️

**Comment by mimorocks** [comment]
yes. I did not have time yet to look into that. will keep trying to get it green :)

**Comment by bravo-kernel** [comment]
take all the time you need, I will probably not be able to review/merge until this Friday anyway. Appreciate it 👍

**Comment by mimorocks** [comment]
I am not really used to working with travis and/or phpunit/phpcs
I have still one failing step. phpcs seems to be missing? but I don't know why. @bravo-kernel  any ideas?

`The command "sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./config --ignore=.webroot; fi"" exited with 2. `

**Comment by bravo-kernel** [comment]
Not an idea but... I can share how I have always done it from day one.

I always take https://github.com/UseMuffin/Slug as an example of how things should be done (as those maintainers know what they are doing) and then compare what they have in their `travis.yml` and try to mimic that. E.g.

- https://github.com/UseMuffin/Slug/blob/master/.travis.yml#L40
- https://github.com/UseMuffin/Slug/blob/master/.travis.yml#L46

🤞

**Comment by bravo-kernel** [comment]
@mimo74 ohhhh, please ignore my previous comment, I was too fast, my bad.

Phpcs is functioning perfectly fine as it is.

There are styling errors in the travis log, see for example https://travis-ci.org/alt3/cakephp-swagger/jobs/655381117#L733 which:

- tells us `routes.php` has 3 problems
- directly below that tells us what error on which line

Fix those 3, push the changes and you will see the list of styling errors decrease. Fix until solved.

**Comment by bravo-kernel** [comment]
Also, it appears the styling errors are unrelated to your change. These are probably new rule sets now triggering the errors because it has been ages since the last release. I don't want to over-ask you here but if you could fix them that would be awesome.

**Comment by bravo-kernel** [comment]
Sorry for spamming you, two last things:

- there is [phpcbf to auto-fix issues](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically), just make sure to pass the cakephp rules
- if you are unable I will be able to fix these somewhere this weekend

**Comment by mimorocks** [comment]
> Phpcs is functioning perfectly fine as it is.

ohh... i see.. the lines before where the output of phpcs. I got confused by `exited with 2` and interpreted that as `not found`.

**Comment by bravo-kernel** [comment]
No worries, phpcs is really good stuff.

**Comment by mimorocks** [comment]
we are green!

**Comment by bravo-kernel** [comment]
This is all you man, congrats. I will eat something first, then merge and release a new 4.0.0 version.

Awesome job 💯

**Comment by bravo-kernel** [comment]
Released as https://github.com/alt3/cakephp-swagger/releases/tag/4.0.0
Packagist updated as well https://packagist.org/packages/alt3/cakephp-swagger

Looks gtm, thanks for this one, really appreciated

**Comment by bravo-kernel** [comment]
image

**Pull request merged**
